// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnFWmOFt3NJ-OBmly67EOrP3uWM_V03OI',
    appId: '1:419097121301:web:78ea550b2018cb9620741c',
    messagingSenderId: '419097121301',
    projectId: 'pulsera-hrms',
    authDomain: 'pulsera-hrms.firebaseapp.com',
    storageBucket: 'pulsera-hrms.firebasestorage.app',
    measurementId: 'G-JMD1B6PM62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz2MTZnqUWY4hG6JF3pGKlgV6f6UQiF5I',
    appId: '1:419097121301:android:a320971ae1133c8920741c',
    messagingSenderId: '419097121301',
    projectId: 'pulsera-hrms',
    storageBucket: 'pulsera-hrms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWBeA8aBJoZfDTj1CDLV4KogUA_lNzxNM',
    appId: '1:419097121301:ios:2051b3a65b20262720741c',
    messagingSenderId: '419097121301',
    projectId: 'pulsera-hrms',
    storageBucket: 'pulsera-hrms.firebasestorage.app',
    iosBundleId: 'com.pulsera.hrms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWBeA8aBJoZfDTj1CDLV4KogUA_lNzxNM',
    appId: '1:419097121301:ios:247fd867d78091d120741c',
    messagingSenderId: '419097121301',
    projectId: 'pulsera-hrms',
    storageBucket: 'pulsera-hrms.firebasestorage.app',
    iosBundleId: 'com.pulsera.hrms.pulsera',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnFWmOFt3NJ-OBmly67EOrP3uWM_V03OI',
    appId: '1:419097121301:web:6d07b1cdcb8a666620741c',
    messagingSenderId: '419097121301',
    projectId: 'pulsera-hrms',
    authDomain: 'pulsera-hrms.firebaseapp.com',
    storageBucket: 'pulsera-hrms.firebasestorage.app',
    measurementId: 'G-Y8MV8CWNVE',
  );
}
